name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World!
        run: echo "Hello World!"
    steps:
      - name: Date
        run: date
    steps:
      - name: directory
        run: ls -l